---
title: "A5_Solution"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Create sample climate data

```{r}

n_days = 365

ppt <- rnorm(n_days, mean = 320, sd = 75)
pet <- rnorm(n_days, mean = 2000, sd = 500)
aet <- rnorm(n_days, mean = 900, sd = 100)
tmax <- rnorm(n_days, mean = 10.5, sd = 3)
tmin <- rnorm(n_days, mean = 7.5, sd = 3)
date <- seq(as.Date("2018/1/1"), as.Date("2018/12/31"), "days")

clim <- data.frame(ppt = ppt, pet = pet, aet = aet, tmax = tmax, tmin = tmin, date = date)

```

##Function Group 1: Summarize Data 
```{r}

## Mean summer precipitation
## Summer calendar days of the year: 151 to 241

library(stringr)

calc_mean_summer_ppt <- function(clim) {
clim$date<- as.character(clim$date)

jun <- clim %>% filter(str_detect(date, "-06-"))
jul <- clim %>% filter(str_detect(date, "-07-"))
aug <- clim %>% filter(str_detect(date, "-08-"))

summer_months <- rbind(jun, jul, aug)

sum_avg_ppt <- mean(summer_months$ppt)

return(sum_avg_ppt)
}

calc_mean_summer_ppt(clim)

## Find which days of the year have the most extreme climate values
## This only works if the last column is date!

find_extreme_dates <- function(clim, min_xtreme = FALSE) {
  
# Change data format so date is the rowname
col_num <- which(colnames(clim)=="date" )
clim_tmp <- clim[,-col_num]
rownames(clim_tmp) <- clim[,col_num]

clim_var_names <- colnames(clim_tmp)

# Create temp data frame for maximums
tmp_data <- data.frame(clim_var = clim_var_names, max = NA, day = NA)

for (i in 1:length(clim_tmp)) {
  tmp_data$max[i] = max(clim_tmp[i])
}

xtreme_dates <- rownames(clim_tmp)[apply(clim_tmp,2,which.max)]

tmp_data$day <- xtreme_dates

tmp_data2 <- data.frame("Climate Variable" = clim_var_names, "Maximum Value" = tmp_data$max, Date = tmp_data$day)

if(min_xtreme) {
  
  min_data <- data.frame(clim_var = clim_var_names, min = NA, day = NA)

for (i in 1:length(clim_tmp)) {
  min_data$min[i] = min(clim_tmp[i])
}

xtreme_min_dates <- rownames(clim_tmp)[apply(clim_tmp,2,which.min)]

min_data$day <- xtreme_dates

min_data2 <- data.frame("Climate Variable" = clim_var_names, "Minimum Value" = min_data$min, Date = min_data$day)

return(Minimums = min_data2)
}

else(return(Maximums = tmp_data2))

}

find_extreme_dates(clim)

```

##Function Group 2A: Heat Stress Index 

```{r}

# Let's pretend there is a species that has a heat stress index of:
# Under 7 degrees = 0
# 7-9 degrees = 1
# 9-11 degrees = 2
# Over 11 degrees = 3

# Let's find how many days of the year that it will be under each value of heat stress and total days where it goes under heat stress.

# First, let's find the average temperature

calc_HI <- function(clim, low, med, high) {

avg_temp <- data.frame(avg_tmp = NA, date = clim$date, "heat index" = NA)

for (i in 1:nrow(avg_temp)) {
  avg_temp$avg_tmp[i] = (clim$tmax[i]+clim$tmin[i])/2
}

# Now, let's assign heat index values for each of the average temperatures

for (i in 1:nrow(avg_temp)) {
  avg_temp$heat.index[i] = ifelse(avg_temp$avg_tmp[i] < low, 0, avg_temp$heat.index[i]) 
  avg_temp$heat.index[i] = ifelse(avg_temp$avg_tmp[i] > low & avg_temp$avg_tmp[i] < med, 1, avg_temp$heat.index[i])
  avg_temp$heat.index[i] = ifelse(avg_temp$avg_tmp[i] > med & avg_temp$avg_tmp[i] < high, 2, avg_temp$heat.index[i])
  avg_temp$heat.index[i] = ifelse(avg_temp$avg_tmp[i] > high, 3, avg_temp$heat.index[i])
}

zero <- sum(avg_temp$heat.index==0)
one <- sum(avg_temp$heat.index==1)
two <- sum(avg_temp$heat.index==2)
three <- sum(avg_temp$heat.index==3)

heat_index <- c("0", "1","2", "3")
count_days <- c(zero, one, two, three)

HI_count <- data.frame("Heat Index" = heat_index, "Number of Days"=count_days)

return(HI_count)
}

poopoo <- calc_HI(clim, 7, 9, 11)


## Function that calculates drought stress

# Calculate CWD

cwd_clim <- data.frame(aet = clim$aet, pet = clim$pet, cwd = NA, drought_stress = NA, avg_cwd = NA)
for (i in 1:nrow(clim)) {
  cwd_clim$cwd[i] = clim$pet[i]-clim$aet[i]
}

# Calculate average CWD over a period of 7 days 
last_row = nrow(cwd_clim) - 6

# If average is under Xmm, then the species will likely dessicate

for ( i in 7:last_row) {
  cwd_clim$avg_cwd[i] = mean(cwd_clim$cwd[i-6],cwd_clim$cwd[i-5],cwd_clim$cwd[i-4],cwd_clim$cwd[i-3], cwd_clim$cwd[i-2],cwd_clim$cwd[i-1],cwd_clim$cwd[i], cwd_clim$cwd[i+6],cwd_clim$cwd[i+5],cwd_clim$cwd[i+4],cwd_clim$cwd[i+3], cwd_clim$cwd[i+2],cwd_clim$cwd[i+1])
  
  cwd_clim$drought_stress[i] = ifelse(cwd_clim$avg_cwd[i] > 900, 1, 0)
}


```






